# Contains all SQL keywords supported by the Basic SQL Formatter.
# Expanded to cover: DML, DDL, DCL, TCL, stored procedures, transactions,
# window functions, CTEs, subqueries, constraints, indexes, views, and more.


# ── Single-word SQL keywords ──────────────────────────────────────────────────
SQL_KEYWORDS = [

    # Core DML (Data Manipulation Language)
    "SELECT",
    "FROM",
    "WHERE",
    "INSERT",
    "INTO",
    "VALUES",
    "UPDATE",
    "SET",
    "DELETE",
    "MERGE",
    "UPSERT",

    # Core DDL (Data Definition Language)
    "CREATE",
    "TABLE",
    "ALTER",
    "DROP",
    "TRUNCATE",
    "RENAME",
    "COLUMN",
    "DATABASE",
    "SCHEMA",
    "VIEW",
    "INDEX",
    "SEQUENCE",
    "TRIGGER",
    "PROCEDURE",
    "FUNCTION",
    "DOMAIN",
    "TYPE",
    "TEMP",
    "TEMPORARY",
    "VIRTUAL",
    "MATERIALIZED",

    # DCL (Data Control Language)
    "GRANT",
    "REVOKE",
    "DENY",
    "PRIVILEGE",
    "PRIVILEGES",
    "ROLE",
    "USER",
    "PUBLIC",
    "OPTION",

    # TCL (Transaction Control Language)
    "BEGIN",
    "COMMIT",
    "ROLLBACK",
    "SAVEPOINT",
    "RELEASE",
    "TRANSACTION",
    "WORK",
    "CHAIN",
    "ISOLATION",
    "LEVEL",
    "DEFERRED",
    "IMMEDIATE",
    "EXCLUSIVE",

    # Joins
    "JOIN",
    "INNER",
    "LEFT",
    "RIGHT",
    "FULL",
    "OUTER",
    "CROSS",
    "NATURAL",
    "LATERAL",
    "ON",
    "USING",

    # Clauses & Modifiers
    "AS",
    "DISTINCT",
    "HAVING",
    "LIMIT",
    "OFFSET",
    "FETCH",
    "NEXT",
    "ROWS",
    "ONLY",
    "TOP",
    "PERCENT",
    "WITH",
    "TIES",
    "RECURSIVE",
    "UNION",
    "INTERSECT",
    "EXCEPT",
    "MINUS",
    "ALL",
    "ANY",
    "SOME",

    # Sorting
    "ORDER",
    "GROUP",
    "BY",
    "ASC",
    "DESC",
    "NULLS",
    "FIRST",
    "LAST",

    # Conditional / CASE
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "IF",
    "IFNULL",
    "NULLIF",
    "COALESCE",
    "IIF",
    "DECODE",

    # Predicates & Logic
    "AND",
    "OR",
    "NOT",
    "IN",
    "LIKE",
    "ILIKE",
    "BETWEEN",
    "IS",
    "NULL",
    "EXISTS",
    "OVERLAPS",
    "SIMILAR",
    "MATCH",

    # Aggregate Functions
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "STDDEV",
    "VARIANCE",
    "MEDIAN",
    "MODE",
    "PERCENTILE",

    # Window Function Keywords
    "OVER",
    "PARTITION",
    "UNBOUNDED",
    "PRECEDING",
    "FOLLOWING",
    "CURRENT",
    "ROW",
    "RANGE",
    "GROUPS",
    "EXCLUDE",
    "FILTER",
    "WITHIN",

    # Window Functions (ranked)
    "RANK",
    "DENSE_RANK",
    "ROW_NUMBER",
    "NTILE",
    "LEAD",
    "LAG",
    "FIRST_VALUE",
    "LAST_VALUE",
    "NTH_VALUE",
    "CUME_DIST",
    "PERCENT_RANK",

    # String Functions
    "UPPER",
    "LOWER",
    "LENGTH",
    "LEN",
    "TRIM",
    "LTRIM",
    "RTRIM",
    "SUBSTRING",
    "SUBSTR",
    "REPLACE",
    "CONCAT",
    "CONCAT_WS",
    "INSTR",
    "CHARINDEX",
    "PATINDEX",
    "LPAD",
    "RPAD",
    "REPEAT",
    "REVERSE",
    "SPACE",
    "STUFF",
    "FORMAT",
    "SOUNDEX",
    "DIFFERENCE",
    "ASCII",
    "CHAR",
    "UNICODE",
    "NCHAR",
    "STR",
    "QUOTE",
    "INITCAP",
    "TRANSLATE",
    "REGEXP_REPLACE",
    "REGEXP_MATCH",

    # Numeric / Math Functions
    "ABS",
    "CEIL",
    "CEILING",
    "FLOOR",
    "ROUND",
    "TRUNCATE",
    "MOD",
    "POWER",
    "SQRT",
    "EXP",
    "LOG",
    "LOG10",
    "SIGN",
    "PI",
    "RANDOM",
    "RAND",
    "GREATEST",
    "LEAST",
    "DIV",

    # Date / Time Functions
    "NOW",
    "SYSDATE",
    "GETDATE",
    "CURRENT_DATE",
    "CURRENT_TIME",
    "CURRENT_TIMESTAMP",
    "LOCALTIME",
    "LOCALTIMESTAMP",
    "DATE",
    "TIME",
    "YEAR",
    "MONTH",
    "DAY",
    "HOUR",
    "MINUTE",
    "SECOND",
    "DATEADD",
    "DATEDIFF",
    "DATEPART",
    "DATENAME",
    "EXTRACT",
    "DATE_PART",
    "DATE_TRUNC",
    "DATE_FORMAT",
    "STRFTIME",
    "TIMESTAMP",
    "INTERVAL",
    "AGE",
    "EPOCH",
    "TIMEZONE",
    "AT",
    "ZONE",
    "CONVERT",
    "CAST",

    # Type Conversion
    "TRY_CAST",
    "TRY_CONVERT",
    "PARSE",
    "TRY_PARSE",
    "TO_CHAR",
    "TO_DATE",
    "TO_NUMBER",
    "TO_TIMESTAMP",

    # NULL Handling
    "ISNULL",
    "ISNOTNULL",
    "NVL",
    "NVL2",
    "ZEROIFNULL",

    # JSON Functions
    "JSON_VALUE",
    "JSON_QUERY",
    "JSON_OBJECT",
    "JSON_ARRAY",
    "JSON_EXTRACT",
    "JSON_TABLE",
    "JSON_ARRAYAGG",
    "JSON_OBJECTAGG",
    "JSONB",

    # Constraints & Table Options
    "CONSTRAINT",
    "PRIMARY",
    "KEY",
    "FOREIGN",
    "REFERENCES",
    "UNIQUE",
    "CHECK",
    "DEFAULT",
    "AUTO_INCREMENT",
    "IDENTITY",
    "GENERATED",
    "ALWAYS",
    "STORED",
    "VIRTUAL",
    "NULLABLE",
    "DEFERRABLE",
    "INITIALLY",

    # Index Options
    "CLUSTERED",
    "NONCLUSTERED",
    "INCLUDE",
    "CONCURRENTLY",
    "REINDEX",
    "ANALYZE",

    # Stored Procedure / Function Keywords
    "DECLARE",
    "VARIABLE",
    "CURSOR",
    "OPEN",
    "CLOSE",
    "FETCH",
    "DEALLOCATE",
    "EXECUTE",
    "EXEC",
    "CALL",
    "RETURN",
    "RETURNS",
    "LANGUAGE",
    "BODY",
    "BEGIN",
    "END",
    "LOOP",
    "WHILE",
    "FOR",
    "DO",
    "REPEAT",
    "UNTIL",
    "LEAVE",
    "ITERATE",
    "EXIT",
    "CONTINUE",
    "RAISE",
    "SIGNAL",
    "RESIGNAL",
    "EXCEPTION",
    "HANDLER",
    "CONDITION",
    "DETERMINISTIC",
    "VOLATILE",
    "STABLE",
    "IMMUTABLE",
    "SECURITY",
    "DEFINER",
    "INVOKER",
    "CALLED",
    "INPUT",
    "STRICT",
    "PARALLEL",
    "SAFE",
    "UNSAFE",
    "COST",
    "ROWS",
    "NOCACHE",
    "CACHE",
    "CYCLE",
    "NOCYCLE",
    "MINVALUE",
    "MAXVALUE",
    "INCREMENT",

    # Trigger Keywords
    "BEFORE",
    "AFTER",
    "INSTEAD",
    "OF",
    "EACH",
    "STATEMENT",
    "NEW",
    "OLD",
    "REFERENCING",

    # Miscellaneous
    "EXPLAIN",
    "VACUUM",
    "ATTACH",
    "DETACH",
    "PRAGMA",
    "COMMENT",
    "LOCK",
    "UNLOCK",
    "FLUSH",
    "RESET",
    "SHOW",
    "DESCRIBE",
    "DESC",
    "USE",
    "COPY",
    "IMPORT",
    "EXPORT",
    "LOAD",
    "UNLOAD",
    "BULK",
    "OPENROWSET",
    "OPENDATASOURCE",
    "OPENQUERY",
    "LINKED",
    "SERVER",
    "SYNONYM",
    "ASSEMBLY",
    "CLR",
    "EXTERNAL",
    "TABLESAMPLE",
    "NOLOCK",
    "READPAST",
    "UPDLOCK",
    "ROWLOCK",
    "PAGELOCK",
    "TABLOCK",
    "TABLOCKX",
    "HOLDLOCK",
    "SNAPSHOT",
    "READ",
    "WRITE",
    "COMMITTED",
    "UNCOMMITTED",
    "REPEATABLE",
    "SERIALIZABLE",
    "FORCE",
    "STRAIGHT_JOIN",
    "SQL_CALC_FOUND_ROWS",
    "FOUND_ROWS",
    "RETURNING",
    "OUTPUT",
    "INTO",
    "DELETED",
    "INSERTED",
    "PIVOT",
    "UNPIVOT",
    "GROUPING",
    "SETS",
    "CUBE",
    "ROLLUP",
]


# ── Multi-word SQL keywords ───────────────────────────────────────────────────
# Checked BEFORE single-word keywords to prevent partial matches.
MULTI_WORD_KEYWORDS = [

    # Joins
    "INNER JOIN",
    "LEFT JOIN",
    "RIGHT JOIN",
    "FULL OUTER JOIN",
    "LEFT OUTER JOIN",
    "RIGHT OUTER JOIN",
    "CROSS JOIN",
    "NATURAL JOIN",
    "NATURAL LEFT JOIN",
    "NATURAL RIGHT JOIN",

    # Sorting & Grouping
    "ORDER BY",
    "GROUP BY",
    "PARTITION BY",
    "NULLS FIRST",
    "NULLS LAST",

    # Set Operations
    "UNION ALL",
    "UNION DISTINCT",
    "INTERSECT ALL",
    "EXCEPT ALL",

    # DDL
    "CREATE TABLE",
    "CREATE OR REPLACE",
    "CREATE OR REPLACE VIEW",
    "CREATE OR REPLACE PROCEDURE",
    "CREATE OR REPLACE FUNCTION",
    "CREATE OR REPLACE TRIGGER",
    "CREATE TEMP TABLE",
    "CREATE TEMPORARY TABLE",
    "CREATE INDEX",
    "CREATE UNIQUE INDEX",
    "CREATE CLUSTERED INDEX",
    "CREATE NONCLUSTERED INDEX",
    "CREATE VIEW",
    "CREATE MATERIALIZED VIEW",
    "CREATE PROCEDURE",
    "CREATE FUNCTION",
    "CREATE TRIGGER",
    "CREATE SEQUENCE",
    "CREATE SCHEMA",
    "CREATE DATABASE",
    "CREATE USER",
    "CREATE ROLE",
    "ALTER TABLE",
    "ALTER VIEW",
    "ALTER INDEX",
    "ALTER PROCEDURE",
    "ALTER FUNCTION",
    "ALTER TRIGGER",
    "ALTER DATABASE",
    "ALTER SCHEMA",
    "ALTER SEQUENCE",
    "ALTER USER",
    "ALTER ROLE",
    "DROP TABLE",
    "DROP VIEW",
    "DROP INDEX",
    "DROP PROCEDURE",
    "DROP FUNCTION",
    "DROP TRIGGER",
    "DROP SCHEMA",
    "DROP DATABASE",
    "DROP SEQUENCE",
    "DROP USER",
    "DROP ROLE",
    "DROP IF EXISTS",
    "IF EXISTS",
    "IF NOT EXISTS",
    "ADD COLUMN",
    "DROP COLUMN",
    "RENAME COLUMN",
    "RENAME TO",
    "MODIFY COLUMN",
    "ALTER COLUMN",

    # Constraints
    "PRIMARY KEY",
    "FOREIGN KEY",
    "NOT NULL",
    "NOT DEFERRABLE",
    "INITIALLY DEFERRED",
    "INITIALLY IMMEDIATE",
    "ON DELETE CASCADE",
    "ON DELETE SET NULL",
    "ON DELETE RESTRICT",
    "ON DELETE NO ACTION",
    "ON UPDATE CASCADE",
    "ON UPDATE SET NULL",
    "ON UPDATE RESTRICT",
    "ON UPDATE NO ACTION",

    # DML
    "INSERT INTO",
    "INSERT IGNORE",
    "INSERT OR REPLACE",
    "INSERT OR IGNORE",
    "DELETE FROM",
    "MERGE INTO",
    "ON CONFLICT",
    "DO NOTHING",
    "DO UPDATE",

    # Window Frame
    "ROWS BETWEEN",
    "RANGE BETWEEN",
    "GROUPS BETWEEN",
    "UNBOUNDED PRECEDING",
    "UNBOUNDED FOLLOWING",
    "CURRENT ROW",

    # CTEs
    "WITH RECURSIVE",

    # Transactions
    "BEGIN TRANSACTION",
    "BEGIN WORK",
    "START TRANSACTION",
    "COMMIT TRANSACTION",
    "COMMIT WORK",
    "ROLLBACK TRANSACTION",
    "ROLLBACK WORK",
    "ROLLBACK TO",
    "RELEASE SAVEPOINT",
    "SET TRANSACTION",
    "READ ONLY",
    "READ WRITE",
    "READ COMMITTED",
    "READ UNCOMMITTED",
    "REPEATABLE READ",
    "ISOLATION LEVEL",
    "WITH LOCK",
    "FOR UPDATE",
    "FOR SHARE",
    "LOCK IN SHARE MODE",

    # Stored Procedures / Functions
    "AS BEGIN",
    "AS $$",
    "END IF",
    "END LOOP",
    "END WHILE",
    "END FOR",
    "END CASE",
    "IS NOT NULL",
    "IS NULL",
    "NOT IN",
    "NOT LIKE",
    "NOT BETWEEN",
    "NOT EXISTS",
    "NOT ILIKE",

    # Grouping Sets
    "GROUPING SETS",
    "WITH ROLLUP",
    "WITH CUBE",

    # DCL
    "GRANT ALL",
    "GRANT SELECT",
    "GRANT INSERT",
    "GRANT UPDATE",
    "GRANT DELETE",
    "GRANT EXECUTE",
    "REVOKE ALL",
    "WITH GRANT OPTION",
    "WITH ADMIN OPTION",

    # Misc
    "CROSS APPLY",
    "OUTER APPLY",
    "CONNECT BY",
    "START WITH",
    "PRIOR TO",
    "LEVEL IS",
    "BULK INSERT",
    "SELECT INTO",
    "EXEC SP_EXECUTESQL",
    "SET NOCOUNT ON",
    "SET NOCOUNT OFF",
    "FETCH NEXT",
    "FETCH PRIOR",
    "FETCH FIRST",
    "FETCH LAST",
    "FETCH ABSOLUTE",
    "FETCH RELATIVE",
    "ROWS ONLY",
    "PERCENT ROWS",
    "TOP WITH TIES",
    "OVER PARTITION",
    "PIVOT FOR",
    "UNPIVOT FOR",
    "TRY CAST",
    "TRY CONVERT",
]


# ── Keywords that start on a new line ─────────────────────────────────────────
CLAUSE_KEYWORDS = [

    # Core DML clauses
    "SELECT",
    "FROM",
    "WHERE",
    "GROUP BY",
    "HAVING",
    "ORDER BY",
    "LIMIT",
    "OFFSET",
    "FETCH NEXT",
    "ROWS ONLY",

    # Insert / Update / Delete / Merge
    "INSERT INTO",
    "VALUES",
    "UPDATE",
    "SET",
    "DELETE FROM",
    "MERGE INTO",
    "WHEN MATCHED",
    "WHEN NOT MATCHED",
    "OUTPUT",
    "RETURNING",

    # Joins
    "INNER JOIN",
    "LEFT JOIN",
    "RIGHT JOIN",
    "FULL OUTER JOIN",
    "LEFT OUTER JOIN",
    "RIGHT OUTER JOIN",
    "CROSS JOIN",
    "NATURAL JOIN",
    "ON",
    "USING",

    # Set Operations
    "UNION",
    "UNION ALL",
    "INTERSECT",
    "EXCEPT",
    "MINUS",

    # CTEs
    "WITH",
    "WITH RECURSIVE",

    # Window
    "OVER",
    "PARTITION BY",
    "ROWS BETWEEN",
    "RANGE BETWEEN",

    # Transactions
    "BEGIN",
    "BEGIN TRANSACTION",
    "START TRANSACTION",
    "COMMIT",
    "ROLLBACK",
    "SAVEPOINT",
    "RELEASE SAVEPOINT",
    "ROLLBACK TO",
    "SET TRANSACTION",
    "ISOLATION LEVEL",

    # Procedures & Functions
    "DECLARE",
    "EXECUTE",
    "EXEC",
    "CALL",
    "RETURN",

    # DDL clauses
    "CREATE TABLE",
    "ALTER TABLE",
    "DROP TABLE",
    "CREATE INDEX",
    "CREATE VIEW",
    "CREATE PROCEDURE",
    "CREATE FUNCTION",
    "CREATE TRIGGER",

    # Misc
    "PIVOT",
    "UNPIVOT",
    "GROUPING SETS",
    "CONNECT BY",
    "START WITH",
]


# ── Logical operators that appear on new lines ─────────────────────────────────
LOGICAL_OPERATORS = [
    "AND",
    "OR",
    "XOR",
]


# ── Comparison operators ───────────────────────────────────────────────────────
COMPARISON_OPERATORS = [
    # Multi-character first (sorted longest→shortest in formatter already,
    # but keeping them grouped here for readability)
    "<=>",   # NULL-safe equal (MySQL)
    ">=",
    "<=",
    "<>",
    "!=",
    "||",    # string concat / OR in some dialects
    "->",    # JSON arrow (MySQL)
    "->>",   # JSON arrow text (MySQL / PostgreSQL)
    "#>",    # JSON path (PostgreSQL)
    "#>>",   # JSON path text (PostgreSQL)
    "@>",    # contains (PostgreSQL arrays / jsonb)
    "<@",    # contained by (PostgreSQL)
    "&&",    # overlap (PostgreSQL arrays)
    "~",     # regex match (PostgreSQL)
    "~*",    # regex match case-insensitive (PostgreSQL)
    "!~",    # regex no match (PostgreSQL)
    "!~*",   # regex no match case-insensitive (PostgreSQL)
    "=",
    ">",
    "<",
    "+",
    "-",
    "*",
    "/",
    "%",
    "^",     # exponentiation (PostgreSQL)
    "|",     # bitwise OR
    "&",     # bitwise AND
    ">>",    # bitwise right shift
    "<<",    # bitwise left shift
]